#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;

flag=0

echo

function create_user() {
	useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "http://vpn989.com/script/1194-client.conf"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "Username: $Login"
	echo ""
	echo "Password: $Pass"
	echo ""
	echo "Expired: $exp"
	
	echo "thanks for support Vpn989Script"
}

function renew_user() {
    echo "Success ... Account already renewed"
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
	echo "success Delete $uname"
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
		    echo "User Expired List"
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

clear
echo ""
echo -e "\e[31m              _   _              _____ _____  _____" 
echo -e "\e[32m             | | | |            |  _  |  _  ||  _  |"
echo -e "\e[33m             | | | |_ __  _ __  | |_| |\ V / | |_| |"
echo -e "\e[34m             | | | | '_ \| '_ \ \____ |/ _ \ \____ |"
echo -e "\e[35m             \ \_/ / |_) | | | |.___/ / |_| |.___/ /"
echo -e "\e[36m              \___/| .__/|_| |_|\____/\_____/\____/" 
echo -e "\e[32m                   | |"                              
echo -e "\e[35m                   |_|"
echo -e "\e[31m                |================================|"
echo -e "\e[32m                |    AUTO SCRIPT BY VPN989       |"
echo -e "\e[33m                |   WHATSAPP : 0143749392        |"
echo -e "\e[34m                |  TELEGRAM  : @Chandra989       |"
echo -e "\e[35m                |    GROUP   : @Vpn989Group      |"
echo -e "\e[33m                |_______________________________ |"
echo -e "\e[31m                |       COPYRIGHT BY VPN989      |"
echo -e "\e[35m                |================================|
";PS3='Please enter your choice: '
options=("Add User" "Renew User" "Delete User" "User List" "Expired Users" "Restart Server" "Change Password" "Data Usage" "Ram Status" "Monitor" "Download Client" "Change OVPN Port" "Change Dropbear" "Change Squid3" "Update Server" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Add User")
            read -p "Enter username: " Login
            read -p "Enter password: " Pass
            read -p "Enter expired (Day): " masaaktif
	    create_user
	    break
            ;;
        "Renew User")
            read -p "Enter username to renew: " uname
            read -p "Enter expiry date (YYYY-MM-DD): " expdate
            renew_user
            break
            ;;
        "Delete User")
            read -p "Enter username to be removed: " uname
            delete_user
            break
            ;;		
		"User List")
            user-list
            break
            ;;
		"Users Not Expired")
			not_expired_users
			break
			;;
		"Expired Users")
			expired_users
			break
			;;		
		"Restart Server")
			reboot
			break
			;;	
		"Change Password")
			passwd
			break
			;;
		"Data Usage")
			used_data
			break
			;;
		"Ram Status")
		    free -h | grep -v + > /tmp/ramcache
            cat /tmp/ramcache | grep -v "Swap"
            break
              ;;
       "Monitor")
               monssh
                break
	          ;;
        "Download Client")
		       myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "http://antclub.5gbfree.com/autoscript/debian7/1194-client.conf"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo "Download your client config  "
	echo "http://$myip:989/client.tar"
		       break
			   ;;
		"Change OVPN Port")	
            echo "What OpenVPN port would you like  to change to?"
            read -p "Port: " -e -i 1194 PORT
            sed -i "s/port [0-9]*/port $PORT/" /etc/openvpn/1194.conf
            service openvpn restart
            echo "OpenVPN Updated : Port $PORT"
			break
			;;
		"Change Dropbear")	
            echo "What Dropbear port would you like to change to?"
            read -p "Port: " -e -i 443 PORT
            sed -i "s/DROPBEAR_PORT=[0-9]*/DROPBEAR_PORT=$PORT/" /etc/default/dropbear
            service dropbear restart
            echo "Dropbear Updated : Port $PORT"
			break
			;;
        "Change Squid3")	
            echo "What Squid3 port would you like to change to?"
            read -p "Port: " -e -i 8080 PORT
            sed -i "s/http_port [0-9]*/http_port $PORT/" /etc/squid3/squid.conf
            service squid3 restart
            echo "echo "Squid3 Updated : Port $PORT""
			break
			;;
        "Update Server")
         apt-get update
          break
           ;;		  
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done | lolcat